name: Build Haskell sample

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["9.6.1", "9.4.5"]
        cabal: ["3.8"]
    name: Build on GHC ${{ matrix.ghc }}

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache@v3
        name: Caching
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-build-ghc-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: ${{ runner.os }}-build-ghc-${{ matrix.ghc }}-

      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies all

      - name: Build
        run: cabal run
