name: Build C sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: icu string comparison
      run: make run

    - name: run sort
      run: make helloworld

    - name: versions
      run: make versions
